### ISSUE TITLE
Mention of bare repo directory structure might be typo

### ISSUE THREAD

**Issue by danshick** [maryrosecook/essays#1]
Hey Mary:

First off, fantastic essay. I have been using git for a while now and learned quite a bit from the article, so thanks for taking the time to write it.

I noticed, when discussing the section on bare repos, you mentioned:

> First, all the objects required for the 16 commit on the master branch are copied from alpha/.git/objects/ to delta/.git/objects/.

...when I think it should be:

> First, all the objects required for the 16 commit on the master branch are copied from alpha/.git/objects/ to delta/objects/.

On the very next line, your github master reads:

> Second, refs/heads/master is updated on delta to point at the 16 commit.

...but the copy [here](https://codewords.recurse.com/issues/two/git-from-the-inside-out) reads:

> Second, .git/refs/heads/master is updated on delta to point at the 14 commit.

So I think you already noticed, but only changed it in one place.

**Comment by maryrosecook** [comment]
Hiya! Thanks so much for your comments! They are super helpful.  I'm about to remove this `essays` repo - I have replaced it with the `maryrosecook.com` repo which has the whole content for my website.  I've made the fixes you suggested to that repo and pushed them to my website.

Thanks again!
